def budget_categories
  home = ::Budget::Category.create(name: 'Home')
  home.budget_subcategories.create(name: 'Mortgage/Rent')
  home.budget_subcategories.create(name: 'Electricity')
  home.budget_subcategories.create(name: 'Gas/Oil')
  home.budget_subcategories.create(name: 'Water/Sewer/Trash')
  home.budget_subcategories.create(name: 'Phone')
  home.budget_subcategories.create(name: 'Cable/Satellite')
  home.budget_subcategories.create(name: 'Internet')
  home.budget_subcategories.create(name: 'Furnishings/Appliances')
  home.budget_subcategories.create(name: 'Lawn/Garden')
  home.budget_subcategories.create(name: 'Home Supplies')
  home.budget_subcategories.create(name: 'Maintenance')
  home.budget_subcategories.create(name: 'Improvements')
  home.budget_subcategories.create(name: 'Other')

  daily_living = ::Budget::Category.create(name: 'Daily Living')
  daily_living.budget_subcategories.create(name: 'Groceries')
  daily_living.budget_subcategories.create(name: 'Personal Supplies')
  daily_living.budget_subcategories.create(name: 'Clothing')
  daily_living.budget_subcategories.create(name: 'Cleaning Services')
  daily_living.budget_subcategories.create(name: 'Dining/Eating Out')
  daily_living.budget_subcategories.create(name: 'Dry Cleaning')
  daily_living.budget_subcategories.create(name: 'Salon/Barber')
  daily_living.budget_subcategories.create(name: 'Other')

  income = ::Budget::Category.create(name: 'Income')
  income.budget_subcategories.create(name: 'Wages')
  income.budget_subcategories.create(name: 'Interest Income')
  income.budget_subcategories.create(name: 'Dividends')
  income.budget_subcategories.create(name: 'Gifts Received')
  income.budget_subcategories.create(name: 'Refunds/Reimbursements')
  income.budget_subcategories.create(name: 'Other')

  transportation = ::Budget::Category.create(name: 'Transportation')
  transportation.budget_subcategories.create(name: 'Vehicle Payments')
  transportation.budget_subcategories.create(name: 'Fuel')
  transportation.budget_subcategories.create(name: 'Bus/Taxi/Train Fare')
  transportation.budget_subcategories.create(name: 'Repairs')
  transportation.budget_subcategories.create(name: 'Registration/License')
  transportation.budget_subcategories.create(name: 'Other')

  health = ::Budget::Category.create(name: 'Health')
  health.budget_subcategories.create(name: 'Doctor/Dentist')
  health.budget_subcategories.create(name: 'Medicine/Drugs')
  health.budget_subcategories.create(name: 'Health Club Dues')
  health.budget_subcategories.create(name: 'Emergency')
  health.budget_subcategories.create(name: 'Other')

  insurance = ::Budget::Category.create(name: 'Insurance')
  insurance.budget_subcategories.create(name: 'Auto')
  insurance.budget_subcategories.create(name: 'Health')
  insurance.budget_subcategories.create(name: 'Home/Rental')
  insurance.budget_subcategories.create(name: 'Life')
  insurance.budget_subcategories.create(name: 'Other')

  education = ::Budget::Category.create(name: 'Education')
  education.budget_subcategories.create(name: 'Tuition')
  education.budget_subcategories.create(name: 'Books')
  education.budget_subcategories.create(name: 'Music lessons')
  education.budget_subcategories.create(name: 'Other')

  charity = ::Budget::Category.create(name: 'Charity')
  charity.budget_subcategories.create(name: 'Gifts Given')
  charity.budget_subcategories.create(name: 'Charitable Donations')
  charity.budget_subcategories.create(name: 'Religious Donations')
  charity.budget_subcategories.create(name: 'Other')

  savings = ::Budget::Category.create(name: 'Savings')
  savings.budget_subcategories.create(name: 'Emergency Fund')
  savings.budget_subcategories.create(name: 'Transfer to Savings')
  savings.budget_subcategories.create(name: 'Retirement (401k)')
  savings.budget_subcategories.create(name: 'Investments')
  savings.budget_subcategories.create(name: 'College')
  savings.budget_subcategories.create(name: 'Other')

  obligations = ::Budget::Category.create(name: 'Obligations')
  obligations.budget_subcategories.create(name: 'Student Loan')
  obligations.budget_subcategories.create(name: 'Other Loan')
  obligations.budget_subcategories.create(name: 'Credit Card #1')
  obligations.budget_subcategories.create(name: 'Credit Card #2')
  obligations.budget_subcategories.create(name: 'Federal Taxes')
  obligations.budget_subcategories.create(name: 'Property Tax')
  obligations.budget_subcategories.create(name: 'State/Local Taxes')
  obligations.budget_subcategories.create(name: 'Legal Fees')
  obligations.budget_subcategories.create(name: 'Other')

  entertainment = ::Budget::Category.create(name: 'Entertainment')
  entertainment.budget_subcategories.create(name: 'Videos/DVDs')
  entertainment.budget_subcategories.create(name: 'Music')
  entertainment.budget_subcategories.create(name: 'Games')
  entertainment.budget_subcategories.create(name: 'Rentals')
  entertainment.budget_subcategories.create(name: 'Movies/Theater')
  entertainment.budget_subcategories.create(name: 'Concerts/Plays')
  entertainment.budget_subcategories.create(name: 'Books')
  entertainment.budget_subcategories.create(name: 'Hobbies')
  entertainment.budget_subcategories.create(name: 'Film/Photos')
  entertainment.budget_subcategories.create(name: 'Sports')
  entertainment.budget_subcategories.create(name: 'Outdoor recreation')
  entertainment.budget_subcategories.create(name: 'Toys/Gadgets')
  entertainment.budget_subcategories.create(name: 'Other')

  subscriptions = ::Budget::Category.create(name: 'Subscriptions')
  subscriptions.budget_subcategories.create(name: 'Newspaper')
  subscriptions.budget_subcategories.create(name: 'Magazines')
  subscriptions.budget_subcategories.create(name: 'Dues')
  subscriptions.budget_subcategories.create(name: 'Club Memberships')
  subscriptions.budget_subcategories.create(name: 'Other')

  vacation = ::Budget::Category.create(name: 'Vacation')
  vacation.budget_subcategories.create(name: 'Travel')
  vacation.budget_subcategories.create(name: 'Lodging')
  vacation.budget_subcategories.create(name: 'Food')
  vacation.budget_subcategories.create(name: 'Rental Car')
  vacation.budget_subcategories.create(name: 'Entertainment')
  vacation.budget_subcategories.create(name: 'Other')

  miscellaneous = ::Budget::Category.create(name: 'Miscellaneous')
  miscellaneous.budget_subcategories.create(name: 'Bank Fees')
  miscellaneous.budget_subcategories.create(name: 'Postage')
  miscellaneous.budget_subcategories.create(name: 'Other')
end
