inherit_from:
  - '.rubocop_base.yml'

# TODO
Metrics/AbcSize:
  Max: 201

# Wont Fix
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Rails/FindBy:
  Enabled: false
