AllCops:
  RunRailsCops: true
  Include:
    - 'Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'lib/templates/**/*'
    - 'db/schema.rb'
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/AlignParameters:
  Enabled: false
