AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/templates/**/*'
Rails:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - '**/*.jbuilder'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/IndentationConsistency:
  EnforcedStyle: "rails"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'
